### ISSUE TITLE
How to generate data files under the /data directory

### ISSUE THREAD

**Issue by Yijie-Shi0829** [tae898/explicit-memory#2]
Hi, I'm wondering how you guys get the data files under the data directory. If possible, Could you please provide the code for generating these csv files? Thank you so much!

**Comment by tae898** [comment]
Hi,

You meant this? https://github.com/tae898/room-env/tree/main/room_env/data

**Comment by Yijie-Shi0829** [comment]
The directory data/v1-question_prob=1.0 . There are csv files about test_total_reward_mean, train_episode_average loss blablabla. I'm just wondering how you generate these files. I went through the code of the whole repo and did not find the code that generates these files.

**Comment by tae898** [comment]
Oh they are generated by running training:

```sh
python train.py --config train.yaml
```

**Comment by Yijie-Shi0829** [comment]
Thank you!
